FROM centos:<%= @tag %>
MAINTAINER Taiki Sugawara <buzztaiki@gmail.com>

RUN yum -y install man sysstat
<%- if /centos[67]/.match(@tag) -%>
# install sysstat man pages
RUN yum -y --setopt=tsflags= reinstall sysstat
<%- end -%>

COPY entrypoint /

ENTRYPOINT ["/entrypoint"]
