#!/bin/bash

set -e
ARGV=("$@")

read_stdin() {
  FILE=$(mktemp -p /tmp docker-sysstat.XXXXXXXXXX)
  cat > "$FILE"
}

has_option() {
  local x y
  for x in "${ARGV[@]}"; do
    for y in "$@"; do
      [ "$x" = "$y" ] && return 0
    done
  done
  return 1
}

watchdog() {
  local interval="$1"
  local now f
  while true; do
    sleep "$interval"
    now="$(date +%s)"
    find /tmp -maxdepth 1 -name 'docker-sysstat.*' | while read f; do
      if (( "$now" - "$(stat -c %Y "$f")" > "$interval" )); then
        rm "$f"
      fi
    done
  done
}

case "$1" in
  sadf)
    has_option "--help" && exec sadf --help
    has_option "-V" "--version" && exec sadf -V
    read_stdin
    exec "$@" "$FILE"
    ;;
  sar)
    has_option "--help" && exec sar --help
    has_option "-V" "--version" && exec sar -V
    read_stdin
    exec "$@" -f "$FILE"
    ;;
  daemon)
    interval="$2"
    watchdog ${interval:-60}
    ;;
  *)
    exec "$@"
esac
