#!/bin/bash

set -e
trap 'rm -f "$FILE"' EXIT

ARGV=("$@")

read_stdin() {
  FILE=$(mktemp)
  cat > "$FILE"
}

has_option() {
  for x in "${ARGV[@]}"; do
    for y in "$@"; do
      [ "$x" = "$y" ] && return 0
    done
  done
  return 1
}

case "$1" in
  sadf)
    has_option "--help" && exec sadf --help
    has_option "-V" "--version" && exec sadf -V
    read_stdin
    exec "$@" "$FILE"
    ;;
  sar)
    has_option "--help" && exec sar --help
    has_option "-V" "--version" && exec sar -V
    read_stdin
    exec "$@" -f "$FILE"
    ;;
  daemon)
    exec tail -f /dev/null
    ;;
  *)
    exec "$@"
esac
